config/routes.rb
PoliticalKickstarter::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  post '/campaigns/editable_form' => "campaigns#editable_form"
  post '/campaigns/finalize_campaign' => "campaigns#finalize_campaign"
  put '/campaigns/finalize_campaign' => "campaigns#finalize_campaign"
  put '/campaigns/toggle_status' => "campaigns#toggle_status"
  post '/campaigns/support' => "campaigns#support"
  put '/campaigns/unsupport' => "campaigns#unsupport"
  get '/campaigns/check_support' => "campaigns#check_support"

  devise_for :users, controllers: {:omniauth_callbacks => 'authentications', 
                                   :registrations => 'registrations',
                                   :sessions => 'sessions',
                                   :passwords => 'passwords'}
  resources :users, only: [:show]
  resources :campaigns do
    resources :matchers
  end
  # resources :topics, only: [:index]

  # resources :campaign_users, only: :create
  post '/donate' => "stripe#donate"
  get '/add_cc' => "stripe#add_cc"
  post '/process_card' => "stripe#process_card"
  get '/' => "home#index"
  post '/filter_topic/:topic' => "campaigns#filter_topic"
  get '/multiauth' => "users#multiauth"
  post '/home/filter' => "home#filter"

  # get 'tags/:tag', to: 'campaigns#index', as: :tag  ==>  uncomment to enable search by tags
  root :to => "home#index"
end

app/models/matcher.rb
class Matcher < ActiveRecord::Base
  attr_accessible :name, :match_amount, :logo_url, :description, :campaign_user_id, :count

  validates_presence_of :name, :campaign_user_id

  belongs_to :campaign_user

end

app/controllers/matchers_controller.rb
class MatchersController < ApplicationController
  include TaggingHelper
  include HomeHelper

  def index
    @user = User.new
    @trending = trending_filter
    @most_funded = most_funded_filter
    @most_successful = most_successful_filter
    @featured = Campaign.where(id: [6, 8, 4])
  end

  def new
    @camp_id = params[:id]
    @matcher = Matcher.new
    respond_to do |format|
      format.html { render partial: 'matchers/new'  }
    end
  end

  def create
    p params
    campaign = Campaign.find params[:matcher][:id]
    campaign_user = current_user.campaign_users.create :campaign_id: campaign.id, :user_type => MATCHER
    @new_matcher = Matcher.new( name:params[:matcher][:name], 
            match_amount: params[:matcher][:match_amount],
                logo_url: params[:matcher][:logo_url],
             description: params[:matcher][:description],
        campaign_user_id: campaign_user.id,
                   count: params[:matcher][:count],
                logo_url: params[:matcher][:logo_url])
    if @new_matcher.save
      
    else
      render json: {error: @new_matcher.errors.full_messages}.to_json, :status => :unprocessable_entity
    end
  end

end

app/views/matchers/_campaign_grid.html.haml
.source
  - trending.each do |campaign|
    = render 'matchers/campaign_snapshot', {klass: 'campaign-snapshot', campaign: campaign}
.trending
  - trending.each do |campaign|
    = render 'matchers/campaign_snapshot', {klass: 'campaign-snapshot', campaign: campaign}
.most-funded
  - most_funded.each do |campaign|
    = render 'matchers/campaign_snapshot', {klass: 'campaign-snapshot', campaign: campaign}
.successes
  - most_successful.each do |campaign|
    = render 'matchers/campaign_snapshot', {klass: 'campaign-snapshot', campaign: campaign}
  

app/views/matchers/_campaign_snapshot.html.haml
%li{class: klass, 'data-id' => campaign.id}
  = link_to image_tag(campaign.image_url), campaign.video_url, class: 'fancybox'
  .campaign-details
    .match_text
      = link_to campaign.title, campaign_path(campaign)
      .creator
        by
        - camp_user = CampaignUser.where(campaign_id: campaign.id).where(user_type: 'Creator')
        - user = User.find(camp_user[0].user_id)
        = link_to user.name, user_path(user)
    .button.match_button
      = link_to 'Match Donations', new_matcher_path
    .stats-1
      .raised #{to_currency(campaign.donation_total)}
      - percent = ((campaign.donation_total / campaign.funding_goal) * 100).to_i
      .percent #{percent}%
    .match_bar
      %span{style: "width: #{percent}%"}
    .stats-2
      - time_array = campaign.separated_time_ago
      .time-left
        %span #{time_array[0]}
        - unless time_array[1] == ""
          #{time_array[1]} left
      .supporters
        %span #{campaign.supporters.length}
        supporters

app/views/matchers/_new.html.haml
= semantic_form_for @matcher, remote: true do |f|
  .form_full
    = f.input :name, label: "On Behalf Of...", placeholder: "Corpotation or Name"
  .form_half
    = f.input :logo_url, label: "Logo Url or Image"
  .form_half
    = f.input :description,  label: "Why are you supporting this cause?"
  .form_half
    = f.input :match_amount, label: "What level would you like match?"
  .form_half
    = f.input :count, label: "How many donors would you like to match at this level?"  
  .form_half
    = f.input :id, :as => :hidden, value: @camp_id
  .form_full
    = f.action :submit

app/views/matchers/index.html.haml
.staance-container
#topic_title_box
  #topic_title
  #topic_description

= render 'home/select_bar'
%ul{class: 'campaign-grid'}
  = render 'matchers/campaign_grid', { trending: @trending, most_funded: @most_funded, most_successful: @most_successful }
.lessfancybox

app/views/matchers/new.html.haml
= semantic_form_for [@campaign, @matcher] do |f|
  .form_full
    = f.input :name, label: "On Behalf Of...", placeholder: "Corpotation or Name"
  .form_half
    = f.input :logo_url, label: "Logo Url or Image"
  .form_half
    = f.input :description,  label: "Why are you supporting this cause?"
  .form_half
    = f.input :match_amount, label: "What level would you like match?"
  .form_half
    = f.input :count, label: "How many donors would you like to match at this level?"
  .form_full
    = f.action :submit