config/routes.rb
PoliticalKickstarter::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  post '/campaigns/editable_form' => "campaigns#editable_form"
  post '/campaigns/finalize_campaign' => "campaigns#finalize_campaign"
  put '/campaigns/finalize_campaign' => "campaigns#finalize_campaign"
  put '/campaigns/toggle_status' => "campaigns#toggle_status"
  post '/campaigns/support' => "campaigns#support"
  put '/campaigns/unsupport' => "campaigns#unsupport"
  get '/campaigns/check_support' => "campaigns#check_support"

  devise_for :users, controllers: {:omniauth_callbacks => 'authentications', 
                                   :registrations => 'registrations',
                                   :sessions => 'sessions',
                                   :passwords => 'passwords'}
  resources :users, only: [:show]
  resources :campaigns do
    resources :matchers
  end
  # resources :topics, only: [:index]

  # resources :campaign_users, only: :create
  post '/donate' => "stripe#donate"
  get '/add_cc' => "stripe#add_cc"
  post '/process_card' => "stripe#process_card"
  get '/' => "home#index"
  post '/filter_topic/:topic' => "campaigns#filter_topic"
  get '/multiauth' => "users#multiauth"
  post '/home/filter' => "home#filter"

  # get 'tags/:tag', to: 'campaigns#index', as: :tag  ==>  uncomment to enable search by tags
  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	include TaggingHelper
	include ResourceHelper  

	def index
    @user = User.new
    @trending = Campaign.trending
    @most_funded = Campaign.most_funded
    @most_successful = Campaign.most_successful
    @featured = Campaign.where(id: [5, 8, 9])
    @topics = Topic.all
  end

  def filter
    render json: render_to_string(partial: 'home/campaign_grid', 
                                  locals: { trending: Campaign.trending(6, params[:topic]),
                                            most_funded: Campaign.most_funded(6, params[:topic]),
                                            most_successful: Campaign.most_successful(6, params[:topic]) }).to_json
  end
end

app/helpers/home_helper.rb
module HomeHelper  
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/views/home/_campaign_grid.html.haml
.source
  - trending.each do |campaign|
    = render 'home/campaign_snapshot', {klass: 'campaign-snapshot', campaign: campaign}
.trending
  - trending.each do |campaign|
    = render 'home/campaign_snapshot', {klass: 'campaign-snapshot', campaign: campaign}
.most-funded
  - most_funded.each do |campaign|
    = render 'home/campaign_snapshot', {klass: 'campaign-snapshot', campaign: campaign}
.successes
  - most_successful.each do |campaign|
    = render 'home/campaign_snapshot', {klass: 'campaign-snapshot', campaign: campaign}
  

app/views/home/_campaign_snapshot.html.haml
.campaign-snapshot#tester{:'data-id' => campaign.id}
  #top_color
  .campaign-details#camp_top
    .text
      = link_to campaign.title, campaign_path(campaign)
      .creator
        by
        - user = campaign.creator
        = link_to user.name, user_path(user)
  .campaign_img
    .shadow
      <li>#{link_to image_tag(campaign.image_url), campaign.video_url, class: 'fancybox'}
  .campaign-details
    .stats-1
      .raised #{to_currency(campaign.donation_total)}
      .percent #{campaign.percent_funded}%
    .bar
      %span{style: "width: #{campaign.percent_funded}%"}
    .stats-2
      - time_array = campaign.separated_time_ago
      .time-left
        %span #{time_array[0]}
        - unless time_array[1] == ""
          #{time_array[1]} left
      .supporters
        %span #{campaign.supporters.length}
        supporters

app/views/home/_featured_campaigns.html.haml
#featured-campaigns
  #featured-video-box
    #featured-video-image-box
      - @featured.each_with_index do |campaign, index|
        #featured-video-image{class: index}
          = link_to image_tag(campaign.image_url), campaign.video_url, class: 'home'
          #shadowlt
          #shadowrt
    #arrow.left
      %i.icon-chevron-left.icon-4x   
    #arrow.right
      %i.icon-chevron-right.icon-4x
%div{style:"margin-top:2px"}   
  #featured-details-box
    #slider-icons
      %i.icon-circle.0.selected
      %i.icon-circle.1
      %i.icon-circle.2
    #featured-details-inner-box
      - @featured.each_with_index do |campaign, index|
        #featured-video-details{class: index}
          = render 'home/featured_video_details', {campaign: campaign}

app/views/home/_featured_video_details.html.haml
#campaign-name-stats
  = link_to campaign.title, campaign, id: 'campaign-name'
  #campaign-stats
    - time_array = campaign.separated_time_ago
    %span #{to_currency(campaign.donation_total)}
    raised &nbsp;&nbsp;|&nbsp;
    %span #{time_array[0]}
    - unless time_array[1] == ""
      #{time_array[1]} left

app/views/home/_select_bar.html.haml
.select-bg
  .select-bar
    = link_to 'TRENDING', '#', id: 'trending', class: 'categories selected'
    = link_to 'MOST FUNDED', '#', id: 'most-funded', class: 'categories'
    = link_to 'SUCCESS STORIES', '#', id: 'successes', class: 'categories'
    = link_to 'TOPICS', root_path, id: 'topics', remote: true
    = render 'home/topic_dropdown'

app/views/home/_topic_dropdown.html.haml
#topic_list
  - @topics.each do |topic|
    = link_to topic.title, home_filter_path(topic: topic.title), method: 'post', remote: true, class: 'topic_list_title', id: topic.description

app/views/home/index.html.haml
#topic_title_box
  #topic_title

= render 'home/featured_campaigns'
= render 'home/select_bar'
%ul{class: 'campaign-grid'}
  = render 'home/campaign_grid', { trending: @trending, most_funded: @most_funded, most_successful: @most_successful }