config/routes.rb
PoliticalKickstarter::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  post '/campaigns/editable_form' => "campaigns#editable_form"
  post '/campaigns/finalize_campaign' => "campaigns#finalize_campaign"
  put '/campaigns/finalize_campaign' => "campaigns#finalize_campaign"
  put '/campaigns/toggle_status' => "campaigns#toggle_status"
  post '/campaigns/support' => "campaigns#support"
  put '/campaigns/unsupport' => "campaigns#unsupport"
  get '/campaigns/check_support' => "campaigns#check_support"

  devise_for :users, controllers: {:omniauth_callbacks => 'authentications', 
                                   :registrations => 'registrations',
                                   :sessions => 'sessions',
                                   :passwords => 'passwords'}
  resources :users, only: [:show]
  resources :campaigns do
    resources :matchers
  end
  # resources :topics, only: [:index]

  # resources :campaign_users, only: :create
  post '/donate' => "stripe#donate"
  get '/add_cc' => "stripe#add_cc"
  post '/process_card' => "stripe#process_card"
  get '/' => "home#index"
  post '/filter_topic/:topic' => "campaigns#filter_topic"
  get '/multiauth' => "users#multiauth"
  post '/home/filter' => "home#filter"

  # get 'tags/:tag', to: 'campaigns#index', as: :tag  ==>  uncomment to enable search by tags
  root :to => "home#index"
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  include ActionView::Helpers::DateHelper
  include ActionView::Helpers::TextHelper

  attr_accessible :topic_id, :image_url, :video_url, :funding_deadline, :stance 
  attr_accessible :short_blurb, :location, :cause_url, :funding_goal, :pitch, :title
  attr_accessible :tag_list, :donation_total, :opposing_campaign_id, :status

  validates_presence_of :title, :short_blurb, :location, :image_url

  has_many :campaign_users
  has_many	:users, through: :campaign_users
  belongs_to :topic

  acts_as_taggable

  [PENDING, ACTIVE, FUNDED, SUSPENDED, UNSUCCESSFUL].each do |stat|
    define_method "#{stat.downcase}?" do
      self.status == stat
    end
  end

  def self.most_funded(num = 9, topic = nil)
    unless topic.nil?
      self.where(topic_id: Topic.find_by_title(topic).id).order("donation_total DESC").limit(num)
    else
      self.order("donation_total DESC").limit(num)
    end
  end

  def self.most_successful(num = 9, topic = nil)
    unless topic.nil?
      self.where(topic_id: Topic.find_by_title(topic).id).order("donation_total/funding_goal DESC").limit(num)
    else
      self.order("donation_total/funding_goal DESC").limit(num)
    end
  end

  def self.trending(num = 9, topic = nil)
    recently_updated = CampaignUser.where("updated_at > ?", 1.week.ago)
    trending_campaign_users = recently_updated.group_by {|camp| camp.campaign_id }
    camp_ids = trending_campaign_users.sort {|camp_id, camps| camps.count}.map {|camp| camp = camp[0]}
    unless topic.nil?
      Campaign.where(topic_id: Topic.find_by_title(topic).id).where(id: camp_ids).limit(num)
    else
      Campaign.where(id: camp_ids).where(status: ACTIVE).limit(num)
    end
    
  end

  def separated_time_ago
    seconds = self.funding_deadline - Time.zone.now
    if seconds > 0
      if seconds / 86400 > 1
        result = { 'day' => (seconds / 86400).to_i }
      elsif seconds % 3600
        result = { 'hour' => (seconds / 3600).to_i }
      else
        result = { 'minute' => (seconds / 60).to_i }
      end
      pluralized = pluralize(result.values.first, result.keys.first) 
      return pluralized.split(' ')
    else
      return ["Campaign funded", ""]
    end
  end

  def after_deadline?
    self.funding_deadline < Date.today
  end

  def before_deadline?
    self.funding_deadline > Date.today
  end

  def display_deadline
    self.funding_deadline.strftime("Funding Deadline: %m/%d/%Y")
  end

  def display_countdown
    self.funding_deadline.strftime("%B%e, %Y %H:%M:%S")
  end

  def campaign_matchers
    Matcher.joins(:campaign_user => :campaign).where("campaigns.id =?", self.id)
  end

  def supporters
    CampaignUser.campaign_supporters(self.id)
  end

  def donors
    CampaignUser.campaign_donors(self.id)
  end

  def creator
    CampaignUser.campaign_creator(self.id)
  end

  def add_supporter(user)
    CampaignUser.create(campaign_id: self.id, user_id: user.id, :user_type => SUPPORTER)
  end

  def remove_supporter(user)
    CampaignUser.where(user_id: user.id, campaign_id: self.id, user_type: SUPPORTER).first.destroy
  end

  def related_campaigns
    topics = Topic.find_by_id(self.topic_id)
    Campaign.where(status: FUNDED).where(topic_id: topics.id)
  end

  def schedule_stripe_payment
    ScheduledWorker.perform_at(self.funding_deadline, self.id)
  end

  def percent_funded
    ((self.donation_total / self.funding_goal) * 100).to_i
  end

  def update_funding_status
    self.status = FUNDED if self.donation_total >= self.funding_goal
    self.save
  end

  def toggle_campaign_status
    new_status = (self.status == PENDING) ? ACTIVE : PENDING
    self.update_attribute(:status, new_status)
    new_status
  end

  def creator
    camp_user = CampaignUser.where('campaign_id = ? and user_type = ?', self.id, "Creator").first
    User.find(camp_user.user_id)
  end

  class << self

    [PENDING, ACTIVE, FUNDED, SUSPENDED, UNSUCCESSFUL].each do |stat|
      define_method "#{stat.downcase}_campaigns" do
        self.where(status: stat)
    end
  end

  end



end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  include CreateFormValidation
  include CampaignHelper

  before_filter :auth_user, :except => [:index, :show]
  before_filter :check_same_user, :only => [:edit, :update, :destroy]

  def index
    @topics = Topic.all
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(params[:campaign])
    # @campaign.campaign_users.build :user => current_user, :user_type => CREATOR
    if @campaign.save
      session[:campaign_build] = @campaign.id
      # remove next line if using Shadi's logic
      CampaignUser.create(campaign_id: @campaign.id, user_id: current_user.id, :user_type => CREATOR)
      render json: {campaign_id: @campaign.id }.to_json
    else
      render json: {error: @campaign.errors.full_messages}.to_json, :status => :unprocessable_entity
    end
  end

  def show
    session.delete(:campaign_id) if session[:campaign_id]
    @campaign = Campaign.find_by_id(params[:id])
    @opposing_campaign = Campaign.find_by_id(@campaign.opposing_campaign_id) if @campaign.opposing_campaign_id
    @campaign_show = CampaignHelper.render_objects_for_view(current_user, @campaign)
  end

  def edit
  end

  def update
    if @campaign.update_attributes(params[:campaign])
      session[:campaign_build] = @campaign.id
      render json: { campaign_id: @campaign.id, campaign_pitch: @campaign.pitch }.to_json
    else
      render json: {error: @campaign.errors.full_messages}.to_json, :status => :unprocessable_entity
    end
  end

  def destroy
    @campaign.update_attribute(:status, SUSPENDED)
    redirect_to current_user, alert: "Campaign Deleted" 
  end

  def toggle_status
    campaign = Campaign.find(params[:id])
    new_status = campaign.toggle_campaign_status
    render json: new_status.to_json
  end

  def support
    camp = Campaign.find_by_id(params[:id])
    camp.add_supporter(current_user)
    count = camp.supporters.count
    render json: count.to_s.to_json
  end

  def unsupport
    camp = Campaign.find_by_id(params[:id])
    camp.remove_supporter(current_user)
    count = camp.supporters.count
    render json: count.to_s.to_json
  end

  def check_support
    # is there a better way to get the campaign_id from the page and pass it to this controller?
    params[:path].match(/(\d)/)
    campaign_id = $1.to_i
    supporter = current_user.supporter?(campaign_id)
    if supporter
      render json: true
    else
      render json: false
    end
  end

  def filter_topic
    topic = Topic.find_by_title(params[:topic])
    campaigns = Campaign.where(topic_id: topic.id)
    render json: render_to_string(partial: 'filtered_opp_campaigns', locals: { camp: campaigns }).to_json
  end

  def editable_form
    if params[:form].length < 520
      errors = "Pitch must be a minimum length of 520 characters"
      render json: errors.to_json 
    else
      @campaign = Campaign.find_by_id(session[:campaign_build])
      @campaign.update_attribute('pitch', params[:form])
      @related_campaigns = @campaign.related_campaigns
      respond_to do |format|
        if @campaign.save
          # Shadi wants us to remove dependency of using in Ruby/Rails... do it?
          format.js { render partial: 'campaigns/editable_form' }
          format.json { render json: @related_campaigns }
        else
          format.json { render json: @campaign.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def finalize_campaign
    errors = CreateFormValidation.form_three_validations(params[:campaign])
    if errors.blank?
      @campaign = Campaign.find_by_id(session[:campaign_build])
      @campaign.update_attributes(params[:campaign])
      if @campaign.save
        @campaign.schedule_stripe_payment
        UserMailer.campaign_new_email(current_user, @campaign).deliver
        session.delete(:campaign_build)
        render nothing: true
      else
        render json: {:error => @campaign.errors.full_messages}.to_json, :status => :unprocessable_entity
      end
    else
      render json: errors.to_json
    end
  end

  protected

    def check_same_user
      @campaign = Campaign.find(params[:id])
      creator = @campaign.creator
      unless creator == current_user
        flash[:alert] = "You can only edit campaigns that you created."
        redirect_to @campaign
      end
    end
    
end

app/helpers/campaign_helper.rb
module CampaignHelper
  extend self

  def render_objects_for_view(current_user, campaign)
    support_ids = campaign.supporters
    donor_ids = campaign.donors
    button_status = (campaign.status == 'Active') ? 'Pause' : 'Activate'
    campaign_show = {
      supporter_count: support_ids.count,
      donor_count: donor_ids.count,
      video: UrlToMediaTag.convert(campaign.video_url, width: 540, height: 320),
      button_status: button_status
    }
  end

  # def set_build_session
  #   session[:campaign_build] = @campaign.id
  # end
end

app/views/campaigns/new/_errors.html.haml
-if errors
  #errors
    - errors.each do |error|
      = error
      %br

app/views/campaigns/new/_example.html.haml
%h1 Title: Call to Action
%img{src: "/assets/campaign.jpg", alt: "Photo that illustrates your staance"}
%h3 The need
%p
  The first paragraph should be no longer than three sentences.  You need to grab
  the readers attention quickly.  What is the key goal of your campaign?
%h3 The Opportunity
%p
  What will happen should your campaign be funded?  How will the 
  world become a better place?  Be realistic and credible.  Your readers will only donate if they find your campaign inspiring and
  possible.
%h3 The Team
%p
  Who are the people behind the campaign?  What is their track record? Why are you the right people to make this work?
%h3 More info
%p
  Provide links to your causes' website for those who want to know more.

app/views/campaigns/new/_form_one.html.haml
.form_head
  #welcome_msg
    = render '/campaigns/new/welcome'
= semantic_form_for @campaign, url: url, remote: true do |f|
  = render '/campaigns/new/errors', :target => @campaign
  .form_full.title
    = f.input :title, placeholder: 'Title'
  .form_half.topic
    = f.input :topic, include_blank: "Choose topic"
  .form_half.right
    = f.input :tag_list, placeholder: "Tags separated by commas"
  .form_half
    = f.input :video_url, placeholder: 'Video URL'
  .form_half.right
    = f.input :image_url, placeholder: 'Image URL'
  .form_half
    = f.input :location, placeholder: 'Location'
  .form_half.right
    = f.input :short_blurb, as: :text, placeholder: 'Short blurb'
  .form_full
    = f.action :submit, label: "Step 2"

app/views/campaigns/new/_form_three.html.haml
.form_head
= semantic_form_for @campaign, :url => campaigns_finalize_campaign_path, remote: true do |f|
  
  .form_half
    = f.input :cause_url, placeholder: "Cause URL"
  .form_half.right
    = f.input :funding_deadline, as: :date_picker, placeholder: "Funding deadline"
  .form_half
    #funding_goal Funding Goal
    = f.input :funding_goal
    = f.hidden_field :opposing_campaign_id

  - unless @related_campaigns.empty?
    .opposing_selection
      #track_opposition Keep track of your opposition
      #tracking_description Select one campaign from below:
      %a.opp_arrow.left{href: "#"}
        %i.icon-chevron-left.icon-3x
      .opposition
        .opp_container
          - @related_campaigns.each do |camp|
            .opp-camp
              = render 'home/campaign_snapshot', {klass: 'campaign-snapshot', campaign: camp}
              = link_to 'Select', '#' , :class => 'select-opposing', :"data-id" => camp.id
      %a.opp_arrow.right{href: "#"}
        %i.icon-chevron-right.icon-3x

  .form_full
    = f.action :submit, label: "Create!"

app/views/campaigns/new/_form_two.html.haml
%script{:src => "//tinymce.cachefly.net/4.0/tinymce.min.js"}
:javascript
  tinymce.init({
      selector: "#editable",
      inline: true,
      plugins: [
          "advlist autolink lists link image charmap print preview anchor",
          "searchreplace visualblocks code fullscreen",
          "insertdatetime media table contextmenu paste"
      ],
      toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
  });
.form_head
#editable{contenteditable: "", onchange: 'sizeBox'}  
  .form_full#edit_magic
    = render "campaigns/new/example"
#campaign_id{:style => 'display: none'}
  = @campaign.id
#cont_button.button
  Step 3
  %i.icon-arrow-right

  

app/views/campaigns/new/_forms.html.haml
.form_head
= semantic_form_for @campaign do |f|
  .form_full.title
    = f.input :title
  .form_half
    = f.input :topic        
  .form_half.right
    = f.input :tag_list, placeholder: "Tags separated by commas"
  .form_half
    = f.input :video_url 
  .form_half.right
    = f.input :image_url
  .form_half
    = f.input :location 
  .form_half.right
    = f.input :short_blurb, as: :text
  .form_full
    = f.action :submit, :value => "Next"

.form_head
  #awesome_campaign{:contenteditable => "true"}  
    .form_full.edit_magic
      = render 'campaigns/new/example'
  %id{:style => 'display: none'}
    = @campaign.id



.form_head
= semantic_form_for @campaign do |f|
  .form_half
    = f.input :cause_url 
  .form_half.right
    = f.input :funding_deadline, as: :date_picker
  .form_half
    = f.input :funding_goal
  .form_full
    = f.action :submit

app/views/campaigns/new/_welcome.html.haml
#welcome_campaign
  %p
    Congratulations! You're now ready for the next step: letting people know why they should fund your campaign.
  %p
    Right now, no one else can see your campaign. You can edit anything you want. When you are satisfied and ready to get funded, click the 'Go Live' button on the last page to make your campaign visible.