config/routes.rb
PoliticalKickstarter::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  post '/campaigns/editable_form' => "campaigns#editable_form"
  post '/campaigns/finalize_campaign' => "campaigns#finalize_campaign"
  put '/campaigns/finalize_campaign' => "campaigns#finalize_campaign"
  put '/campaigns/toggle_status' => "campaigns#toggle_status"
  post '/campaigns/support' => "campaigns#support"
  put '/campaigns/unsupport' => "campaigns#unsupport"
  get '/campaigns/check_support' => "campaigns#check_support"

  devise_for :users, controllers: {:omniauth_callbacks => 'authentications', 
                                   :registrations => 'registrations',
                                   :sessions => 'sessions',
                                   :passwords => 'passwords'}
  resources :users, only: [:show]
  resources :campaigns do
    resources :matchers
  end
  # resources :topics, only: [:index]

  # resources :campaign_users, only: :create
  post '/donate' => "stripe#donate"
  get '/add_cc' => "stripe#add_cc"
  post '/process_card' => "stripe#process_card"
  get '/' => "home#index"
  post '/filter_topic/:topic' => "campaigns#filter_topic"
  get '/multiauth' => "users#multiauth"
  post '/home/filter' => "home#filter"

  # get 'tags/:tag', to: 'campaigns#index', as: :tag  ==>  uncomment to enable search by tags
  root :to => "home#index"
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

  include ActionView::Helpers::DateHelper
  include ActionView::Helpers::TextHelper

  attr_accessible :topic_id, :image_url, :video_url, :funding_deadline, :stance 
  attr_accessible :short_blurb, :location, :cause_url, :funding_goal, :pitch, :title
  attr_accessible :tag_list, :donation_total, :opposing_campaign_id, :status

  validates_presence_of :title, :short_blurb, :location, :image_url

  has_many :campaign_users
  has_many	:users, through: :campaign_users
  belongs_to :topic

  acts_as_taggable

  [PENDING, ACTIVE, FUNDED, SUSPENDED, UNSUCCESSFUL].each do |stat|
    define_method "#{stat.downcase}?" do
      self.status == stat
    end
  end

  def self.most_funded(num = 9, topic = nil)
    unless topic.nil?
      self.where(topic_id: Topic.find_by_title(topic).id).order("donation_total DESC").limit(num)
    else
      self.order("donation_total DESC").limit(num)
    end
  end

  def self.most_successful(num = 9, topic = nil)
    unless topic.nil?
      self.where(topic_id: Topic.find_by_title(topic).id).order("donation_total/funding_goal DESC").limit(num)
    else
      self.order("donation_total/funding_goal DESC").limit(num)
    end
  end

  def self.trending(num = 9, topic = nil)
    recently_updated = CampaignUser.where("updated_at > ?", 1.week.ago)
    trending_campaign_users = recently_updated.group_by {|camp| camp.campaign_id }
    camp_ids = trending_campaign_users.sort {|camp_id, camps| camps.count}.map {|camp| camp = camp[0]}
    unless topic.nil?
      Campaign.where(topic_id: Topic.find_by_title(topic).id).where(id: camp_ids).limit(num)
    else
      Campaign.where(id: camp_ids).where(status: ACTIVE).limit(num)
    end
    
  end

  def separated_time_ago
    seconds = self.funding_deadline - Time.zone.now
    if seconds > 0
      if seconds / 86400 > 1
        result = { 'day' => (seconds / 86400).to_i }
      elsif seconds % 3600
        result = { 'hour' => (seconds / 3600).to_i }
      else
        result = { 'minute' => (seconds / 60).to_i }
      end
      pluralized = pluralize(result.values.first, result.keys.first) 
      return pluralized.split(' ')
    else
      return ["Campaign funded", ""]
    end
  end

  def after_deadline?
    self.funding_deadline < Date.today
  end

  def before_deadline?
    self.funding_deadline > Date.today
  end

  def display_deadline
    self.funding_deadline.strftime("Funding Deadline: %m/%d/%Y")
  end

  def display_countdown
    self.funding_deadline.strftime("%B%e, %Y %H:%M:%S")
  end

  def campaign_matchers
    Matcher.joins(:campaign_user => :campaign).where("campaigns.id =?", self.id)
  end

  def supporters
    CampaignUser.campaign_supporters(self.id)
  end

  def donors
    CampaignUser.campaign_donors(self.id)
  end

  def creator
    CampaignUser.campaign_creator(self.id)
  end

  def add_supporter(user)
    CampaignUser.create(campaign_id: self.id, user_id: user.id, :user_type => SUPPORTER)
  end

  def remove_supporter(user)
    CampaignUser.where(user_id: user.id, campaign_id: self.id, user_type: SUPPORTER).first.destroy
  end

  def related_campaigns
    topics = Topic.find_by_id(self.topic_id)
    Campaign.where(status: FUNDED).where(topic_id: topics.id)
  end

  def schedule_stripe_payment
    ScheduledWorker.perform_at(self.funding_deadline, self.id)
  end

  def percent_funded
    ((self.donation_total / self.funding_goal) * 100).to_i
  end

  def update_funding_status
    self.status = FUNDED if self.donation_total >= self.funding_goal
    self.save
  end

  def toggle_campaign_status
    new_status = (self.status == PENDING) ? ACTIVE : PENDING
    self.update_attribute(:status, new_status)
    new_status
  end

  def creator
    camp_user = CampaignUser.where('campaign_id = ? and user_type = ?', self.id, "Creator").first
    User.find(camp_user.user_id)
  end

  class << self

    [PENDING, ACTIVE, FUNDED, SUSPENDED, UNSUCCESSFUL].each do |stat|
      define_method "#{stat.downcase}_campaigns" do
        self.where(status: stat)
    end
  end

  end



end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  include CreateFormValidation
  include CampaignHelper

  before_filter :auth_user, :except => [:index, :show]
  before_filter :check_same_user, :only => [:edit, :update, :destroy]

  def index
    @topics = Topic.all
  end

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = Campaign.new(params[:campaign])
    # @campaign.campaign_users.build :user => current_user, :user_type => CREATOR
    if @campaign.save
      session[:campaign_build] = @campaign.id
      # remove next line if using Shadi's logic
      CampaignUser.create(campaign_id: @campaign.id, user_id: current_user.id, :user_type => CREATOR)
      render json: {campaign_id: @campaign.id }.to_json
    else
      render json: {error: @campaign.errors.full_messages}.to_json, :status => :unprocessable_entity
    end
  end

  def show
    session.delete(:campaign_id) if session[:campaign_id]
    @campaign = Campaign.find_by_id(params[:id])
    @opposing_campaign = Campaign.find_by_id(@campaign.opposing_campaign_id) if @campaign.opposing_campaign_id
    @campaign_show = CampaignHelper.render_objects_for_view(current_user, @campaign)
  end

  def edit
  end

  def update
    if @campaign.update_attributes(params[:campaign])
      session[:campaign_build] = @campaign.id
      render json: { campaign_id: @campaign.id, campaign_pitch: @campaign.pitch }.to_json
    else
      render json: {error: @campaign.errors.full_messages}.to_json, :status => :unprocessable_entity
    end
  end

  def destroy
    @campaign.update_attribute(:status, SUSPENDED)
    redirect_to current_user, alert: "Campaign Deleted" 
  end

  def toggle_status
    campaign = Campaign.find(params[:id])
    new_status = campaign.toggle_campaign_status
    render json: new_status.to_json
  end

  def support
    camp = Campaign.find_by_id(params[:id])
    camp.add_supporter(current_user)
    count = camp.supporters.count
    render json: count.to_s.to_json
  end

  def unsupport
    camp = Campaign.find_by_id(params[:id])
    camp.remove_supporter(current_user)
    count = camp.supporters.count
    render json: count.to_s.to_json
  end

  def check_support
    # is there a better way to get the campaign_id from the page and pass it to this controller?
    params[:path].match(/(\d)/)
    campaign_id = $1.to_i
    supporter = current_user.supporter?(campaign_id)
    if supporter
      render json: true
    else
      render json: false
    end
  end

  def filter_topic
    topic = Topic.find_by_title(params[:topic])
    campaigns = Campaign.where(topic_id: topic.id)
    render json: render_to_string(partial: 'filtered_opp_campaigns', locals: { camp: campaigns }).to_json
  end

  def editable_form
    if params[:form].length < 520
      errors = "Pitch must be a minimum length of 520 characters"
      render json: errors.to_json 
    else
      @campaign = Campaign.find_by_id(session[:campaign_build])
      @campaign.update_attribute('pitch', params[:form])
      @related_campaigns = @campaign.related_campaigns
      respond_to do |format|
        if @campaign.save
          # Shadi wants us to remove dependency of using in Ruby/Rails... do it?
          format.js { render partial: 'campaigns/editable_form' }
          format.json { render json: @related_campaigns }
        else
          format.json { render json: @campaign.errors.full_messages, status: :unprocessable_entity }
        end
      end
    end
  end
  
  def finalize_campaign
    errors = CreateFormValidation.form_three_validations(params[:campaign])
    if errors.blank?
      @campaign = Campaign.find_by_id(session[:campaign_build])
      @campaign.update_attributes(params[:campaign])
      if @campaign.save
        @campaign.schedule_stripe_payment
        UserMailer.campaign_new_email(current_user, @campaign).deliver
        session.delete(:campaign_build)
        render nothing: true
      else
        render json: {:error => @campaign.errors.full_messages}.to_json, :status => :unprocessable_entity
      end
    else
      render json: errors.to_json
    end
  end

  protected

    def check_same_user
      @campaign = Campaign.find(params[:id])
      creator = @campaign.creator
      unless creator == current_user
        flash[:alert] = "You can only edit campaigns that you created."
        redirect_to @campaign
      end
    end
    
end

app/helpers/campaign_helper.rb
module CampaignHelper
  extend self

  def render_objects_for_view(current_user, campaign)
    support_ids = campaign.supporters
    donor_ids = campaign.donors
    button_status = (campaign.status == 'Active') ? 'Pause' : 'Activate'
    campaign_show = {
      supporter_count: support_ids.count,
      donor_count: donor_ids.count,
      video: UrlToMediaTag.convert(campaign.video_url, width: 540, height: 320),
      button_status: button_status
    }
  end

  # def set_build_session
  #   session[:campaign_build] = @campaign.id
  # end
end

app/views/campaigns/_campaign_tab_logic.html.haml
%ul{class: "tabs_fundraiser"}
  %li{class: "campaign_status", id: "active"}= link_to 'Your Status', '#'
  -if @opposing_campaign
    %li{class: "opposition_status"}= link_to 'Opposition Status', '#'
  %li{class: "comments"}= link_to 'Comments', '#'
#fundraise.unhidden
  = render 'campaigns/fundraise', campaign: @campaign
-if @opposing_campaign
  #opp_status.hidden
    = render '/campaigns/opposition_campaign', campaign: @opposing_campaign
#disqus_thread.hidden
  = render 'shared/disqus'

app/views/campaigns/_editable_form.js.erb
$("#form_three div").html( "<%= j render :partial => '/campaigns/new/form_three' %>"
);

app/views/campaigns/_filtered_opp_campaigns.html.haml
= semantic_form_for "campaign" do |f|
  = f.input :opposing_campaign_id, :as => :select, :collection => camp

app/views/campaigns/_fundraise.html.haml
.fundraise
  .total
    = to_currency(campaign.donation_total)
  #bar
    #progress_bg.small
      #progress{:style => "width: #{(@campaign.donation_total/@campaign.funding_goal)*100}%;"}
    .donation_total
      Raised of
      = to_currency(campaign.funding_goal)
    .deadline
      %i.icon-time
      = campaign.display_deadline
  -if campaign.before_deadline?
    .countdown_value
    .donate
      .contribute
        = form_tag(donate_path, method: "post", remote: true, class: "donate_payment") do
          .dollar_sign
            .icon-usd
          = text_field_tag(:donation, nil, placeholder: 'Amount')
          = hidden_field_tag(:campaign_id, campaign.id)
          = submit_tag("Donate!", class: 'button')
      .countdown
        = campaign.display_countdown
  -else
    .passed_deadline
      Deadline Passed

app/views/campaigns/_header.html.haml
.campaign_header
  .image
    = image_tag @campaign.image_url
  .copy
    - if @campaign.creator == current_user && @campaign.before_deadline?
      - button_text = @campaign_show[:button_status]
      #admin-console
        #admin-title Your Admin Console
        = link_to button_text, campaigns_toggle_status_path(id: @campaign.id), :method => :put, remote: true, id: "status-button", :class => 'button'
        = link_to "Edit", edit_campaign_path, id: "edit-button", :class => 'button'
    .title
      = @campaign.title
    .campaign_creator
      by
      = link_to @campaign.creator.name, user_path(@campaign.creator)
    .location
      = @campaign.location
    .status
      = @campaign.status
    .blurb
      = @campaign.short_blurb

  .user_interaction_summary
    = render 'shared/campaign/social'
    = render 'campaigns/support'
    .supporter_count
      = "Supporters(#{@campaign_show[:supporter_count]})"
    .donor_count
      = "Donors(#{@campaign_show[:donor_count]})"

app/views/campaigns/_pitch.html.haml
.pitch
  .copy_pitch
    = @campaign.pitch.html_safe

app/views/campaigns/_successful_campaign.html.haml
.campaign_completed_banner
  .title 
    Campaign funded!
  .donation_total
    -# create donation_total(campaign) helper method for this
    = 'On ' + campaign.funding_deadline.strftime("%B%e, %Y").to_s + ' this project successfully raised ' + (campaign.donation_total/campaign.funding_goal).to_i.to_s + '% of its funding goal of ' + to_currency(campaign.funding_goal).to_s

app/views/campaigns/_support.html.haml
- if user_signed_in?
  .support_button  
    = link_to "Support", campaigns_support_path(id: @campaign.id), method: 'post', id: "support_link", :class => 'unsupported', remote: true
-else
  .support_button
    = link_to "Support", "#", :class => 'unsupported', id: "support_link"

app/views/campaigns/_unsuccessful_campaign.html.haml
.campaign_completed_banner
  .title 
    Campaign Not Funded
  .donation_total
    Rome was not built in a day...When ready, restart a campaign here:
    %span{id: "link"} 
      = link_to "Create Campaign", new_campaign_path

app/views/campaigns/_video.html.haml
.video_funding
  = @campaign_show[:video]

app/views/campaigns/edit.html.haml
#body
  #head
    #form_one
      %h2
        =render 'campaigns/new/form_one', url: campaign_path
    #form_two{style: "display: none"}
      %h2
        =render 'campaigns/new/form_two'
    #form_three{style: "display: none"}
      %h2
        %div

app/views/campaigns/index.html.haml
.campaigns
  %h2 All Campaigns (by Category)
  - @topics.each do |topic|
    %h3= topic.title
    %ul
      - campaign_by_topic(topic).each do |campaign|
        - if campaign
          %li
            %a{:href => "/campaigns/#{campaign.id}"}= campaign.title

app/views/campaigns/new.html.haml
#body
  #head
    #form_one
      %h2
        =render 'campaigns/new/form_one', url: campaigns_path
    #form_two{style: "display: none"}
      %h2
        =render 'campaigns/new/form_two'
    #form_three{style: "display: none"}
      %h2
        %div

app/views/campaigns/show.html.haml
.campaign
  =render 'campaigns/header'
.story
  .part_one
    - if @campaign.suspended?
      = render 'unsuccessful_campaign', campaign: @campaign
    - elsif @campaign.funded? && @campaign.after_deadline?
      = render 'successful_campaign', campaign: @campaign
    .status_tabs
      = render 'campaigns/campaign_tab_logic'
    =render 'campaigns/video'
    =render 'campaigns/pitch'